// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class auditorium_column_edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auditorium_column_edited));
        
        string IMigrationMetadata.Id
        {
            get { return "202308281403562_auditorium_column_edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
